# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Christian Langlois, An experienced software consultant, available for hire for. Read about my work and recent projects. www.redtoad.co.uk"
baseurl: ""
url: "http://saasbook.home:4000"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

# add on settings

