# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Just a techsailor trial, see URL below."
baseurl: ""
#url: "http://saasbook.home:4000"
url: "https://techsailor.github.io/"
twitter_username: jekyllrb
github_username:  techsailor

# Build settings
markdown: kramdown
permalink: pretty

# add on settings

